### ISSUE TITLE
how to train on custom dataset?

### ISSUE THREAD

**Issue by ucalyptus2** [Picsart-AI-Research/SeMask-Segmentation#7]

**Comment by praeclarumjj3** [comment]
@forkbabu Since our codebase is based on the MMSegmentation library for the Semantic-FPN based decoder and the MaskFormer/Mask2Former repo for MaskFormer/Mask2Former/FaPN decoders. You may look at the source repos for instructions to prepare datasets.

- [Detectron2 datasets used by MaskFormer/Mask2Former](https://github.com/facebookresearch/Mask2Former/blob/main/datasets/README.md)
- [MMSegmentation Datasets](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/dataset_prepare.md#prepare-datasets)
